source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'

target :Wily do
  pod "XCDYouTubeKit", "~> 2.1.1", :inhibit_warnings => true
  pod 'iOS-GTLYouTube', '~> 0.0', :inhibit_warnings => true
  pod 'AFNetworking', '~> 2.5'
  pod 'AFNetworkActivityLogger', '~> 2.0'
  pod 'MXPersistentCache', '~> 0.1'
  pod 'BRYSoundEffectPlayer', '~> 1.0.0'
end
